dist: trusty
language: python
python:
   - "2.6"
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
   - "3.6"
# command to install dependencies
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -y strace
install: "pip install -r test-requirement.txt"
# command to run tests
script: pytest
